add option for speed of encode

diff --git a/bin/reencode b/bin/reencode
--- a/bin/reencode
+++ b/bin/reencode
@@ -2,15 +2,37 @@
 
 # reencode all files in the dir
 
-du -H -c . | tail -n1 | cut -f 1
+usage() {
+    local err=$1
+    local msg=$2
+
+    if [[ -n "$msg" ]] ; then
+        echo "ERROR: $msg"
+        echo
+    fi
+
+    echo "$0 [-h] [-d] [-s]"
+    echo
+    echo "-h  help"
+    echo "-d  dryrun"
+    echo "-s  slower"
+    echo
+
+    exit $err
+}
+
+DRYRUN=""
+while getopts "dsh" opt ; do
+    case $opt in
+        d)  DRYRUN="echo"
+            ;;
+        s)  ;;
+        h)  usage
+            ;;
+    esac
+done
 
 START=$(du -c . | tail -n1 | cut -f 1)
-
-if [[ "$1" == "-d" ]] ; then
-    DRYRUN="echo"
-else
-    DRYRUN=""
-fi
 
 echo "" > remove
 
@@ -18,7 +40,7 @@ for infile in * ; do
     case "$infile" in
         *reencode*) ;;
         *.avi | *.mkv | *.mp4)
-            reencode-file $@ "$infile"
+            reencode-file $@ -f "$infile"
             ;;
     esac
 done && \
@@ -37,4 +59,5 @@ echo "\rm -f remove" >> remove
 
 END=$(du -c . | tail -n1 | cut -f 1)
 
+echo -n "reencode size percent: "
 echo "(${END}-${START}) / ${START}" | bc -l
diff --git a/bin/reencode-file b/bin/reencode-file
--- a/bin/reencode-file
+++ b/bin/reencode-file
@@ -2,19 +2,57 @@
 
 # reencode a single file
 
-if [[ "$1" == "-d" ]] ; then
-    DRYRUN="echo"
-    shift
-else
-    DRYRUN=""
+usage() {
+    local err=$1
+    local msg=$2
+
+    if [[ -n "$msg" ]] ; then
+        echo "ERROR: $msg"
+        echo
+    fi
+
+    echo "$0 [-h] [-d] [-s] <-f filename>"
+    echo
+    echo "-h  help"
+    echo "-d  dryrun"
+    echo "-s  slower"
+    echo
+
+    exit $err
+}
+
+START=$(du -c . | tail -n1 | cut -f 1)
+
+DRYRUN=""
+SPEED="fast"
+while getopts "dshf:" opt ; do
+    case $opt in
+        d)  DRYRUN="echo"
+            ;;
+        s)  SPEED="slower"
+            ;;
+        f)  FILENAME="${OPTARG}"
+            ;;
+        h)  usage
+            ;;
+    esac
+done
+
+if [[ -z "$FILENAME" ]] ; then
+    usage 1 "missing filename"
 fi
 
 di_opts=""
 qual_opts="-crf 21"
 codec="libx265"
-speed="slower"
+speed="$SPEED"
 
-infile="$1"
+infile="$FILENAME"
 
 outfile="${infile}-reencodex265.mkv"
 $DRYRUN ffmpeg -i "${infile}" ${di_opts} ${qual_opts}  -c:v ${codec} -sn -c:a aac ${subtitle} -preset ${speed} "${outfile}"
+
+END=$(du -c . | tail -n1 | cut -f 1)
+
+echo -n "reencode-file size percent: "
+echo "(${END}-${START}) / ${START}" | bc -l
