add option for speed of encode (#39)

diff --git a/bin/reencode-dirs b/bin/reencode-dirs
--- a/bin/reencode-dirs
+++ b/bin/reencode-dirs
@@ -2,22 +2,39 @@
 
 # reencode all subdirs
 
-du -H -c . | tail -n1 | cut -f 1
+usage() {
+    local err=$1
+    local msg=$2
+
+    if [[ -n "$msg" ]] ; then
+        echo "ERROR: $msg"
+        echo
+    fi
+
+    echo "$0 [-h] [-d] [-s]"
+    echo
+    echo "-h  help"
+    echo "-d  dryrun"
+    echo "-s  slower"
+    echo
+
+    exit $err
+}
+
+DRYRUN=""
+while getopts "dsh" opt ; do
+    case $opt in
+        d)  DRYRUN="echo"
+            ;;
+        s)  ;;
+        h)  usage
+            ;;
+    esac
+done
 
 START=$(du -c . | tail -n1 | cut -f 1)
 
-if [[ "$1" == "-d" ]] ; then
-    DRYRUN="echo"
-else
-    DRYRUN=""
-fi
-
 echo "" > remove
-
-di_opts=""
-qual_opts="-crf 21"
-codec="libx265"
-speed="fast"
 
 for indir in */; do
     pushd "$indir"
@@ -35,4 +52,5 @@ echo "\rm -f remove" >> remove
 
 END=$(du -c . | tail -n1 | cut -f 1)
 
+echo -n "reencode-dirs size percent: "
 echo "(${END}-${START}) / ${START}" | bc -l
